# Generated by Django 2.2 on 2022-08-30 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=200)),
                ('tc', models.BooleanField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etypeid', models.IntegerField()),
                ('etypename', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeid', models.IntegerField()),
                ('typename', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_name', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('mode', models.CharField(blank=True, choices=[('CASH', 'cash'), ('CHEQUE', 'cheque'), ('DEMAND DRAFT', 'demand draft')], max_length=15, null=True)),
                ('reason', models.TextField(blank=True, max_length=300, null=True)),
                ('income_by', models.CharField(blank=True, max_length=100, null=True)),
                ('bankname', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('chequeordd', models.IntegerField(blank=True, default=None, null=True)),
                ('dateinbank', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('details', models.TextField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('mode', models.CharField(blank=True, choices=[('CASH', 'cash'), ('CHEQUE', 'cheque'), ('DEMAND DRAFT', 'demand draft')], max_length=15, null=True)),
                ('reason', models.TextField(blank=True, max_length=300, null=True)),
                ('expense_by', models.CharField(blank=True, max_length=100, null=True)),
                ('bankname', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('chequeordd', models.IntegerField(blank=True, default=None, null=True)),
                ('dateinbank', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('details', models.TextField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
