# Generated by Django 3.2 on 2024-12-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20241201_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='mode',
            field=models.CharField(blank=True, choices=[('CASH', 'cash'), ('CHEQUE', 'cheque'), ('DEMAND DRAFT', 'demand draft'), ('Transfer', 'transfer')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='chequeordd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='mode',
            field=models.CharField(blank=True, choices=[('CASH', 'cash'), ('CHEQUE', 'cheque'), ('DEMAND DRAFT', 'demand draft'), ('Transfer', 'transfer')], max_length=15, null=True),
        ),
    ]
